# Generated by Django 4.2 on 2023-04-20 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisordersContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("definition", ckeditor.fields.RichTextField()),
                ("signs", ckeditor.fields.RichTextField()),
                ("advices", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
