# Generated by Django 4.2 on 2023-04-22 09:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_mentaluser_email_alter_mentaluser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "mentaluser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("major", models.CharField(max_length=100)),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("base.mentaluser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "mentaluser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("base.mentaluser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="mentaluser",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Consultant", "Consultant")],
                default="student",
                max_length=20,
            ),
        ),
    ]
