# Generated by Django 4.2 on 2023-04-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_consultant_student_mentaluser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultant",
            options={"verbose_name": "Consultant"},
        ),
        migrations.AlterModelOptions(
            name="mentaluser",
            options={"verbose_name": "Mental User"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student"},
        ),
    ]
