# Generated by Django 4.2 on 2023-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_consultant_options_alter_mentaluser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="profilePicture",
            field=models.ImageField(
                default="user.png", null=True, upload_to="profilePicture/"
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="resume",
            field=models.FileField(null=True, upload_to="resumes/"),
        ),
    ]
