# Generated by Django 4.2 on 2023-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_consultant_profilepicture_consultant_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentaluser",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
