# Generated by Django 4.2 on 2023-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_mentaluser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentaluser",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Consultant", "Consultant")],
                default="student",
                max_length=20,
            ),
        ),
    ]
