# Generated by Django 4.2 on 2023-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_mentaluser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="endTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="startTime",
            field=models.TimeField(),
        ),
    ]
