# Generated by Django 4.2 on 2023-04-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaledFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scale", models.CharField(max_length=10)),
                ("notes", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.session"
                    ),
                ),
            ],
        ),
    ]
