# Generated by Django 4.2 on 2023-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_feedback"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="WebsiteFeedback",
        ),
        migrations.AddField(
            model_name="disorderscontent",
            name="Category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
