# Generated by Django 4.2 on 2023-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_scaledfeedback_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="endTime",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="startTime",
            field=models.TimeField(null=True),
        ),
    ]
