# Generated by Django 4.2 on 2023-04-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_consultant_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultant",
            options={"verbose_name": "Consultant"},
        ),
    ]
