# Generated by Django 4.2 on 2023-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_consultant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
