# Generated by Django 4.2 on 2023-04-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_consultant_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="consultant",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="mentaluser",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
    ]
