# Generated by Django 4.2 on 2023-04-30 22:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_consultant_managers_alter_mentaluser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="consultant",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="mentaluser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
