# Generated by Django 4.2 on 2023-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_consultant_managers_alter_mentaluser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="endTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="major",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="profilePicture",
            field=models.ImageField(
                blank=True, default="user.png", null=True, upload_to="profilePicture/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="startTime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
