# Generated by Django 4.2 on 2023-05-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_consultant_endtime_alter_consultant_major_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultant",
            name="status",
        ),
    ]
