# Generated by Django 4.2 on 2023-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_remove_consultant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="endTime",
            field=models.TimeField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="startTime",
            field=models.TimeField(blank=True, default=9, null=True),
        ),
    ]
