# Generated by Django 4.2 on 2023-05-03 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_alter_consultant_endtime_alter_consultant_starttime"),
    ]

    operations = [
        migrations.AddField(
            model_name="disorderscontent",
            name="NavbarName",
            field=models.CharField(default="none", max_length=150),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="endTime",
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="startTime",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
