# Generated by Django 4.2 on 2023-05-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_disorderscontent_navbarname_alter_consultant_endtime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("18_to_25", "18 to 25"),
                            ("26_to_35", "26 to 35"),
                            ("36_to_50", "36 to 50"),
                            ("over_50", "Over 50"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "symptoms_duration",
                    models.CharField(
                        choices=[
                            ("less_than_3_months", "Less than 3 months"),
                            ("3_to_6_months", "3 to 6 months"),
                            ("1_to_3_years", "1 to 3 years"),
                            ("over_3_years", "Over 3 years"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level_of_functioning",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "family_history",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                        max_length=10,
                    ),
                ),
                (
                    "preferred_treatment",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("therapy", "Therapy"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "symptoms",
                    models.CharField(
                        choices=[
                            (
                                "DepressionSymptoms",
                                "Persistent feelings of hopelessness or emptiness, Loss of interest or pleasure in activities, Difficulty sleeping or focusing, and Changes in your appetite or weight.",
                            ),
                            (
                                "BipolarSymptoms",
                                "Extreme mood swings that include emotional highs (mania or hypomania) and lows (depression), Feeling you can do risky behaviours, and Disturbed periods of sleep (needing either minimal or a lot)",
                            ),
                            (
                                "AnxietySymptoms",
                                "Excessive and persistent worry or fear, physical symptoms (can include restlessness, muscle tension, trembling, sweating, rapid heartbeat, shortness of breath), and Increased heart rate or breathing rapidly.",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.student"
                    ),
                ),
            ],
        ),
    ]
