# Generated by Django 4.2 on 2023-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="symptoms",
            field=models.CharField(
                choices=[
                    (
                        "Depression",
                        "Persistent feelings of hopelessness or emptiness, Loss of interest or pleasure in activities, Difficulty sleeping or focusing, and Changes in your appetite or weight.",
                    ),
                    (
                        "Bipolar",
                        "Extreme mood swings that include emotional highs (mania or hypomania) and lows (depression), Feeling you can do risky behaviours, and Disturbed periods of sleep (needing either minimal or a lot)",
                    ),
                    (
                        "Anxiety",
                        "Excessive and persistent worry or fear, physical symptoms (can include restlessness, muscle tension, trembling, sweating, rapid heartbeat, shortness of breath), and Increased heart rate or breathing rapidly.",
                    ),
                ],
                max_length=25,
            ),
        ),
    ]
