# Generated by Django 4.2 on 2023-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_alter_consultant_endtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="symptoms",
            field=models.CharField(
                choices=[
                    (
                        "Depression",
                        "Persistent feelings of hopelessness or emptiness, Loss of interest or pleasure in activities, Difficulty sleeping or focusing, and Changes in your appetite or weight.",
                    ),
                    (
                        "PTSD",
                        "Thoughts or memories of a traumatic event, Dissociative symptoms, such as feeling detached from oneself or from reality, and Increased arousal, such as difficulty sleeping or being easily startled.",
                    ),
                    (
                        "Anxiety",
                        "Excessive and persistent worry or fear, physical symptoms (can include restlessness, muscle tension, trembling, sweating, rapid heartbeat, shortness of breath), and Increased heart rate or breathing rapidly.",
                    ),
                    ("Consultation", "None of the answers."),
                ],
                max_length=25,
            ),
        ),
    ]
