# Generated by Django 4.2 on 2023-05-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_alter_test_symptoms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scaledfeedback",
            old_name="scale",
            new_name="stage",
        ),
    ]
