# Generated by Django 4.2 on 2023-05-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_rename_scale_scaledfeedback_stage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scaledfeedback",
            old_name="stage",
            new_name="scale",
        ),
    ]
