# Generated by Django 4.2 on 2023-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="sessionEndTime",
            field=models.TimeField(null=True),
        ),
    ]
