# Generated by Django 4.2 on 2023-05-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0035_session_sessionendtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="sessionEndTime",
        ),
    ]
