# Generated by Django 4.2 on 2023-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_session_sessionendtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="sessionEndTime",
            field=models.DateTimeField(null=True),
        ),
    ]
